baseURL = "https://pytransparency.dev/"
title = "PyPI Transparency"
locale = "en-US"
theme = "xmin"
disableKinds = ["taxonomy", "term"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "A proposal for auditable package distribution on Python package indexes."
  repoURL = "https://github.com/trailofbits/pypi-transparency"
  pepURL = "https://github.com/trailofbits/pypi-transparency/blob/main/peps/pep-xxxx.rst"
  footer = "&copy; {Year} PyPI Transparency | [GitHub](https://github.com/trailofbits/pypi-transparency)"

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "Test log"
  url = "https://log.pytransparency.dev"
  weight = 2

[[menus.main]]
  name = "Draft PEP"
  url = "https://github.com/trailofbits/pypi-transparency/blob/main/peps/pep-xxxx.rst"
  weight = 3

[[menus.main]]
  name = "GitHub"
  url = "https://github.com/trailofbits/pypi-transparency"
  weight = 4
